### ISSUE TITLE
PaymentPerformer PaymentType Advance и чек

### ISSUE THREAD

**Issue by Timashkov** [evotor/integration-library#215]
При реализации своего сервиса оплаты в объект PaymentSystem выствляю PaymentType.ADVANCE, однако в чеке печатается строка "Наличные".

**Comment by Timashkov** [comment]
Есть какие-то новости по таске ?

Для примера часть кода сервиса, реализующего комбооплату. В чеке 2 типа оплаты, добавляемые по очереди. Оплата наличными в чеке отбивается корректно, тогда как авансовый платеж пишется как оплата картой. Должен отбиваться как авансовый платеж.

 override fun createProcessors(): MutableMap<String, ActionProcessor> {
        val map = HashMap<String, ActionProcessor>()

        map.put(PaymentSystemEvent.NAME_ACTION,
                object : PaymentSystemProcessor() {
                    // Операция продажи товара
                    override fun sell(action: String, event: PaymentSystemSellEvent, callback: ActionProcessor.Callback) {
                        
                        if (event.accoundId == PAYMENT_SYSTEM_ADVANCE) {
                            var rrn = ""
                            val random = Random()
                            for (i in 0..9) {
                                rrn += random.nextInt(10)
                            }
                            val slip = ArrayList<String>()
                            callback.onResult(PaymentSystemPaymentOkResult(rrn, slip, "ANY STRING", PaymentType.ADVANCE))
                            return
                        }

                        if (event.description == "CASH" || event.accoundId == "-1") {
                            callback.onResult(PaymentSystemPaymentOkResult(rrn, slip, "CASH", PaymentType.CASH))
                            return
                        }

                        val receipt = ReceiptApi.getReceipt(this@PaymentService, Receipt.Type.SELL)
                        if (receipt == null) {
                            callback.skip()
                            return
                        }
                        var price = 0.toBigDecimal()

                        val uuids = receipt.getPositions().map { it.uuid }.toTypedArray()

                        receipt.getPositions().forEach {
                            price += it.price * it.quantity
                        }
                    }
                })
        return map
    }

**Comment by capcom6** [comment]
Вообще говоря, комбо-оплату необходимо реализовывать через https://developer.evotor.ru/docs/beta/doc_java_combined_payment.html
Сам сервис вида оплаты у нас успешно отражает АВАНС строкой, аналогичной Вашей:
`callback.onResult(new PaymentSystemPaymentOkResult(UUID.randomUUID().toString(), slip, null, PaymentType.ADVANCE));`

Совмещая свои сервис комбо-оплаты и вида оплаты у нас получилось (с некоторыми оговорками) реализовать как раз описываемую Вами схему.

**Comment by Timashkov** [comment]
> Вообще говоря, комбо-оплату необходимо реализовывать через https://developer.evotor.ru/docs/beta/doc_java_combined_payment.html
> Сам сервис вида оплаты у нас успешно отражает АВАНС строкой, аналогичной Вашей:
> `callback.onResult(new PaymentSystemPaymentOkResult(UUID.randomUUID().toString(), slip, null, PaymentType.ADVANCE));`
> 
> Совмещая свои сервис комбо-оплаты и вида оплаты у нас получилось (с некоторыми оговорками) реализовать как раз описываемую Вами схему.

Вопрос в том, что это за оговорки. У меня как раз так и сделано: сервис комбооплаты, который предлагает на выбор несколько вариантов. Один из них - оплата авансом. В приведенном ранее примере она есть.

 if (event.accoundId == PAYMENT_SYSTEM_ADVANCE) {
                        var rrn = ""
                        val random = Random()
                        for (i in 0..9) {
                            rrn += random.nextInt(10)
                        }
                        val slip = ArrayList<String>()
                        callback.onResult(PaymentSystemPaymentOkResult(rrn, slip, "ANY STRING", PaymentType.ADVANCE))
                        return
                    }

После обновления прошивки кассы неделю назад теперь эта строка попадает в чек как наличные. В кассе считается как приход денег.

**Comment by capcom6** [comment]
В Вашем примере кода это не сервис комбо-оплаты, это сервис своего способа оплаты. Это 2 разных сервиса.

Проверили только что на ОС 3.9.7.2, EvotorPOS 6.26.3, ККТ 4805, описанный мною ранее способ корректно отражает "ПРЕДВАРИТЕЛЬНАЯ ОПЛАТА (АВАНС)".

**Comment by capcom6** [comment]
А почему Вы для оплаты наличными не используете стандартный PaymentPerformer?
То есть пусть Ваш кастомный сервис оплаты умеет возвращать только ADVANCE, а для случая наличных используйте стандартный ru.evotor.paymentSystem.cash.base

**Comment by Timashkov** [comment]
Похоже мне нужны разъяснения
1)

> В Вашем примере кода это не сервис комбо-оплаты, это сервис своего способа оплаты. Это 2 разных сервиса.

Согласно докуметации , сервис комбооплаты принимает в качестве результата : 

PaymentDelegatorSelectedEventResult.kt – выбрана платёжная система, с помощью которой будет совершён платёж. Результат содержит объект PaymentPurpose
PaymentDelegatorCanceledEventResult.kt – пользователь отменил выбранный способ оплаты.
PaymentDelegatorCanceledAllEventResult.kt – пользователь отменил все способы оплаты. В этом случае смарт-терминал последовательно отменяет все выбранные способы оплаты.

Таким обаразом, прямо из комбооплаты вернуть 

> Сам сервис вида оплаты у нас успешно отражает АВАНС строкой, аналогичной Вашей:
> `callback.onResult(new PaymentSystemPaymentOkResult(UUID.randomUUID().toString(), slip, null, PaymentType.ADVANCE));`

возможности нет. Поэтому я возвращаю ссылку на свой сервис в качестве PaymentPerformer'а. 

2)

> А почему Вы для оплаты наличными не используете стандартный PaymentPerformer?
> То есть пусть Ваш кастомный сервис оплаты умеет возвращать только ADVANCE, а для случая наличных используйте стандартный ru.evotor.paymentSystem.cash.base

Потому что в предыдущей версии библиотеки разработчика такой возможности нет. Однако, она предусмотрена в коде выбора способа оплаты из всех имеющихся и после обновления версий уже могу ее удалить.

**Comment by capcom6** [comment]
1. Все верно, но я Вам предлагаю возвращать ссылку на Ваш сервис только тогда, когда нужен способ оплаты АВАНС, а для наличных использовать п.2.
2. Честно, даже не знаю что там есть в стандартной библиотеке на эту тему, мы используем свою дополнительную библиотеку, в которой данный PaymentPerformer уже давно есть.

В общем, я предполагаю, что EvotorPOS неадекватно переваривает если один сервис оплаты возвращает 2 разных способа оплаты, то есть если ограничиться 1 способом оплаты ADVANCE - все может заработать (во всяком случае у нас - работает).

**Comment by Timashkov** [comment]
> 1. Все верно, но я Вам предлагаю возвращать ссылку на Ваш сервис только тогда, когда нужен способ оплаты АВАНС, а для наличных использовать п.2.
> 2. Честно, даже не знаю что там есть в стандартной библиотеке на эту тему, мы используем свою дополнительную библиотеку, в которой данный PaymentPerformer уже давно есть.
> 
> В общем, я предполагаю, что EvotorPOS неадекватно переваривает если один сервис оплаты возвращает 2 разных способа оплаты, то есть если ограничиться 1 способом оплаты ADVANCE - все может заработать (во всяком случае у нас - работает).

Так вот в том-то и дело, что сейчас вторая ветка не работает совсем. В нее больше не приходим, тк срабатывает теперь стандартный перформер. У Вас в ответе 
callback.onResult(new PaymentSystemPaymentOkResult(UUID.randomUUID().toString(), slip, null, PaymentType.ADVANCE));  
на месте третьего параметра действительно стоит null, или это для примера ?

**Comment by capcom6** [comment]
Строка из работающего приложения.

**Comment by Timashkov** [comment]
> Строка из работающего приложения.

Тогда еще вопрос, на всякий случай, эта строка возвращает результат в обработчик от кассы, никаких других шаманств не происходит ? Просто я бы еще согласился, если бы только в чеке была ошибка, но и в отчете кассы платеж проходит как входящий, а не как аванс. То есть увеличивается сумма на кассе.
Далее, в манифесте на сервис добавляли мета параметры какие-либо , кроме документированных ? По коду библиотек разработки нашел , что там можно добавить мета тег, что платежный сервис для аванса.

**Comment by Timashkov** [comment]
Сделал просто платежный сервис в пару к комбооплате - все равно наличные.

**Comment by xcam** [comment]
Приложите код объявления сервиса в AndroidManifest, пожалуйста

**Comment by xcam** [comment]
На вашей кассе устаревшая версия прошивки ККМ - 4253. Это версия, которая не поддерживает ФФД 1.05. В ней в принципе нет типа оплаты Аванс. Терминалы в рынке на этой прошивке не соответствуют закону с 1.1.2019 и должны быть обновлены
Вам необходимо произвести обновление прошивки - инструкции вам вышлет менеджер

**Comment by Timashkov** [comment]
Спасибо, перепрошивка помогла.
