### ISSUE TITLE
Агентские реквизиты

### ISSUE THREAD

**Issue by ak0nst** [evotor/integration-library#268]
AgentRequisites.createForAgent () принимает: ИНН, ListOF(телефоны поставщиков)
но по закону еще нужно указывать название поставщика.
Подскажите пожалуйста как их добавить в чек

**Comment by capcom6** [comment]
Создавайте напрямую через конструктор класса AgentRequisites, там Вы можете указать любой набор реквизитов поставщика.

**Comment by ak0nst** [comment]
исправлено в rc02-v0.5.01
