### ISSUE TITLE
Min sdk-version 22 in docs. And you have a minimum of 23.

### ISSUE THREAD

**Issue by Worik42** [evotor/integration-library#273]
![Screenshot from 2019-10-16 09-06-37](https://user-images.githubusercontent.com/22797149/66883497-5f38da00-eff8-11e9-8da2-547649a04b04.png)
![Screenshot from 2019-10-16 09-05-54](https://user-images.githubusercontent.com/22797149/66883498-5f38da00-eff8-11e9-937a-89fbb53e9be4.png)

**Comment by xcam** [comment]
Fixed
