### ISSUE TITLE
Добавление реквизитов покупателя в чек

### ISSUE THREAD

**Issue by ak0nst** [evotor/integration-library#278]
На странице документации: https://developer.evotor.ru/docs/doc_java_purchase_requisites_event_processing.html
ИНН (допустимо указать серию и номер паспорта, если покупателем является физическое лицо).
По факту при попытке передать что-то отличное от валидного ИНН получаю: чек аннулирован.

**Comment by capcom6** [comment]
В поле documentNumber допускается указывать только ИНН (дополненный до 12 знаков нулями в начале) или 12 нулей, если ИНН нет.
Номер паспорта необходимо добавлять к наименованию покупателя.
