### ISSUE TITLE
Проблемы с подключение библиотеки

### ISSUE THREAD

**Issue by Zomdies** [evotor/integration-library#357]
![image](https://user-images.githubusercontent.com/49834018/103804576-f0c0bb80-5084-11eb-8c53-1dc93a702d8e.png)
![image](https://user-images.githubusercontent.com/49834018/103804603-fae2ba00-5084-11eb-971e-3d0c9ecab80a.png)
![image](https://user-images.githubusercontent.com/49834018/103804621-01713180-5085-11eb-9063-083281f9a318.png)
Создал чистый проект и пытаюсь установить библиотеку, выдаёт следующею ошибку

**Comment by DarkTwistter** [comment]
Добрый день, аналогичная проблема. Не подскажите, удалось решить?
